//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeUnionBureauSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assistance
    {
        public int AssistanceID { get; set; }
        public Nullable<int> NumberProfcardReceived { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> PaymentCriteriaID { get; set; }
        public Nullable<decimal> Summa { get; set; }
        public Nullable<int> ExtractFromProtocol { get; set; }
        public Nullable<int> MonthID { get; set; }
    
        public virtual Months Months { get; set; }
        public virtual PaymentCriteria PaymentCriteria { get; set; }
    }
}
