//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeUnionBureauSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int CheckInID { get; set; }
        public Nullable<int> NumberProfcardCheckIn { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> StartCheckIn { get; set; }
        public Nullable<System.DateTime> EndCheckIn { get; set; }
        public Nullable<int> AccommodationID { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
    }
}
